[theme]
primaryColor = "#4facfe"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
maxUploadSize = 10
enableXsrfProtection = true
port = 9501
headless = true

[browser]
gatherUsageStats = false
